[package]
name = "export_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "^1.3"
rust_xlsxwriter = "^0.68.0"
serde = { version = "^1.0", features = ["derive"] }
anyhow = "^1.0"
thiserror = "^1.0"